use role accountadmin;

Create role if not exists TRANSFORM;
Grant Role TRANSFORM TO ROLE ACCOUNTADMIN;

Create Warehouse if not exists COMPUTE_WH ;
Grant operate on warehouse COMPUTE_WH TO ROLE TRANSFORM;

Create user if not exists dbt
 PASSWORD = 'dbtPasword123'
 LOGIN_NAME = 'dbt'
 MUST_CHANGE_PASSWORD = FALSE
 DEFAULT_WAREHOUSE = 'COMPUTE_WH'
 DEFAULT_ROLE = TRANFORM
 DEFAULT_NAMESPACE = 'Netflix.RAW'
 COMMENT = 'user for transformation in dbt';
 
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt;

Create Database if not exists Netflix;
Create schema if not exists Netflix.RAW;

GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE Netflix TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE Netflix TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE Netflix TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA Netflix.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA Netflix.RAW TO ROLE TRANSFORM;






